image:
  file: .gitpod.Dockerfile

ports:
- port: 8080 # Web preview
  onOpen: open-preview
- port: 6080 # VNC
  onOpen: open-browser
- port: 6942
  onOpen: ignore
- port: 5900
  onOpen: ignore
- port: 5037
  onOpen: ignore
- port: 9100
  onOpen: ignore

tasks:
- before: >
    source ~/.bashrc
  init: >
    flutter upgrade &&
    flutter update-packages --force-upgrade &&
    flutter doctor &&
    flutter run -d web-server --no-resident # prebuilds the app
  command: >
    flutter run -d web-server --web-port=8080 --web-hostname=0.0.0.0
#    flutter build apk # build android apk
#    flutter build appbundle # disable code shrinker

# You can run Android Studio using:
#/home/gitpod/android-studio/bin/studio.sh
# then open vnc view
