name: stocks

environment:
  sdk: ">=2.1.0 <3.0.0"

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0
  intl_translation: 0.17.7
  http: 0.12.0+2
  isolate: 2.0.2

  analyzer: 0.36.4
  args: 1.5.2
  async: ^2.5.0
  charcode: 1.3.1
  collection: ^1.15.0
  convert: 2.1.1
  crypto: 2.1.3
  csslib: 0.16.1
  dart_style: 1.2.9
  front_end: 0.1.19
  glob: 1.2.0
  html: 0.14.0+3
  http_parser: 3.1.3
  js: 0.6.1+1
  kernel: 0.3.19
  meta: ^1.3.0
  node_interop: 1.0.3
  node_io: 1.0.1+2
  package_config: 1.1.0
  path: ^1.8.0
  pedantic: 1.8.0+1
  petitparser: 2.4.0
  pub_semver: 1.4.2
  source_span: ^1.8.0
  string_scanner: ^1.1.0
  term_glyph: ^1.2.0
  typed_data: 1.3.0
  vector_math: 2.1.0
  watcher: 0.9.7+12
  yaml: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  archive: 2.0.10
  boolean_selector: ^2.1.0
  file: 5.1.0
  image: 2.1.4
  json_rpc_2: 2.1.0
  matcher: 0.12.10
  quiver: 2.0.5
  stack_trace: ^1.10.0
  stream_channel: ^2.1.0
  test_api: 0.4.2
  vm_service_client: 0.2.6+2
  web_socket_channel: 1.1.0
  xml: 3.5.0

flutter:
  uses-material-design: true

# PUBSPEC CHECKSUM: d061
